#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="v1.5.7d"
URL="https://github.com/zencart/zencart/archive/refs/tags/$VERSION.zip"

dl $URL /usr/local/src

