#!/bin/sh -ex

DB_NAME=zencart
DB_USER=zencart
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com
DOMAIN=www.example.com

SRC=/usr/local/src
WEBROOT=/var/www/zencart

# unpack and configure
unzip $SRC/zen-cart-*.zip -d $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/zen-cart-* $WEBROOT
rm $SRC/zen-cart-*.zip
chown -R root:root $WEBROOT
chown -R www-data:www-data $WEBROOT/pub
chown -R www-data:www-data $WEBROOT/media
chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/images
chown -R www-data:www-data $WEBROOT/admin/backups
chown -R www-data:www-data $WEBROOT/admin/images/graphs
chown -R www-data:www-data $WEBROOT/includes/languages/english/html_includes

mv $WEBROOT/includes/dist-configure.php $WEBROOT/includes/configure.php 
mv $WEBROOT/admin/includes/dist-configure.php $WEBROOT/admin/includes/configure.php 

chown www-data:www-data $WEBROOT/includes/configure.php 
chown www-data:www-data $WEBROOT/admin/includes/configure.php 

# tweak php.ini
PHPINI=/etc/php5/apache2/php.ini
sed -i "s|^;date.timezone.*|date.timezone = \"UTC\"|" $PHPINI

# configure apache
a2dissite default
a2ensite zencart
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
ZC_ROOT=$(echo $WEBROOT | sed "s/\//%2F/g")
ZC_CACHE=$(echo $WEBROOT/cache | sed "s/\//%2F/g")

URL="http://127.0.0.1/zc_install/index.php?main_page="
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL "${URL}license" --data "submit=Continue"
$CURL "${URL}license" --data "license_consent=agree&submit=Continue"
$CURL "${URL}inspect" --data "submit=+Install+&zcinst%5Blanguage%5D=english&zcinst%5BDIR_FS_SQL_CACHE%5D=$ZC_CACHE"
$CURL "${URL}database_setup" --data "db_type=mysql&db_coll=utf8&db_host=localhost&db_username=$DB_USER&db_pass=$DB_PASS&db_name=$DB_NAME&db_prefix=&cache_type=none&sql_cache_dir=$ZC_CACHE&submit=Save+Database+Settings&zcinst%5Blanguage%5D=english&zcinst%5BDIR_FS_SQL_CACHE%5D=$ZC_CACHE"
$CURL "${URL}system_setup" --data "physical_path=$ZC_ROOT&virtual_http_path=http%3A%2F%2F$DOMAIN&virtual_https_server=https%3A%2F%2F$DOMAIN&virtual_https_path=https%3A%2F%2F$DOMAIN&enable_ssl=false&enable_ssl_admin=true&submit=Save+System+Settings&zcinst%5Blanguage%5D=english&zcinst%5BDIR_FS_SQL_CACHE%5D=$ZC_CACHE&zcinst%5BDB_TYPE%5D=mysql&zcinst%5BDB_PREFIX%5D=&zcinst%5BDB_CHARSET%5D=utf8&zcinst%5BDB_SERVER%5D=localhost&zcinst%5BDB_SERVER_USERNAME%5D=$DB_USER&zcinst%5BDB_SERVER_PASSWORD%5D=$DB_PASS&zcinst%5BDB_DATABASE%5D=$DB_NAME&zcinst%5BSQL_CACHE_METHOD%5D=none"
$CURL "${URL}config_checkup&action=write"

## fix db password - weird bug!
CONF=$WEBROOT/includes/configure.php 
sed -i "s|DB_SERVER_PASSWORD.*|DB_SERVER_PASSWORD', '$DB_PASS');|" $CONF
CONF=$WEBROOT/admin/includes/configure.php 
sed -i "s|DB_SERVER_PASSWORD.*|DB_SERVER_PASSWORD', '$DB_PASS');|" $CONF

$CURL "${URL}store_setup" --data "store_name=TurnKey+ZenCart&store_owner=Admin&store_owner_email=$EMAIL&store_country=223&store_zone=0&store_address=Store+Name%0D%0A++Address%0D%0A++Country%0D%0A++Phone&store_default_language=en&store_default_currency=USD&demo_install=true&submit=Save+Store+Settings&zcinst%5Blanguage%5D=english"
$CURL "${URL}admin_setup" --data "admin_username=$ADMIN_NAME&admin_pass=${ADMIN_PASS}1&admin_pass_confirm=${ADMIN_PASS}1&admin_email=$EMAIL&submit=Save+Admin+Settings"
$CURL "${URL}finished"

rm -f /tmp/cookie
rm -rf $WEBROOT/zc_install

# set admin password (installer requires number)
SALT="1a"
HASH=$(echo -n ${SALT}${ADMIN_PASS} | md5sum | cut -d " " -f 1)
$MYSQL_BATCH --execute "UPDATE $DB_NAME.admin SET admin_pass=\"${HASH}:${SALT}\" WHERE admin_name=\"admin\";"

# perform tweaks so user isn't asked to reset password
DATE=$(date +"%Y-%m-%d %H:%M:%S")
$MYSQL_BATCH --execute "UPDATE $DB_NAME.admin SET pwd_last_change_date=\"$DATE\" WHERE admin_name=\"admin\";"
$MYSQL_BATCH --execute "UPDATE $DB_NAME.admin SET last_login_date=\"$DATE\" WHERE admin_name=\"admin\";"
$MYSQL_BATCH --execute "UPDATE $DB_NAME.admin SET reset_token=\"\" WHERE admin_name=\"admin\";"

# secure sensitive files
chmod 640 $WEBROOT/includes/configure.php 
chmod 640 $WEBROOT/admin/includes/configure.php 

# stupid security through obscurity
mv $WEBROOT/admin $WEBROOT/manage

# stop services
/etc/init.d/mysql stop
/etc/init.d/apache2 stop

