#!/bin/bash -e
# regenerate zencart mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/var/www/zencart/includes/configure.php
sed -i "s|DB_SERVER_PASSWORD.*|DB_SERVER_PASSWORD', '$PASSWORD');|" "$CONF"

CONF=/var/www/zencart/manage/includes/configure.php
sed -i "s|DB_SERVER_PASSWORD.*|DB_SERVER_PASSWORD', '$PASSWORD');|" "$CONF"

$INITHOOKS_PATH/bin/mysqlconf.py --user=zencart --pass="$PASSWORD"
unset PASSWORD
chown root:www-data \
    /var/www/zencart/includes/configure.php \
    /var/www/zencart/manage/includes/configure.php
chmod 0640 \
    /var/www/zencart/includes/configure.php \
    /var/www/zencart/manage/includes/configure.php
